CREATE DATABASE SANDBOX_DB;

CREATE OR REPLACE SECRET GITHUB_SECRET
  TYPE = password
  USERNAME = 'JJJJ'
  PASSWORD = 'XXXCCCCCCC';

  SHOW SECRETS;

CREATE OR REPLACE API INTEGRATION GITHUB_API_INTEGRATION
  API_PROVIDER = GIT_HTTPS_API
  API_ALLOWED_PREFIXES = ('https://github.com/xxxx/snowflake_data_engineering')
  ALLOWED_AUTHENTICATION_SECRETS = (GITHUB_SECRET)
  ENABLED = TRUE;

show  API INTEGRATIONS;

-- Git Repository
CREATE OR REPLACE GIT REPOSITORY GIT_REPO
  API_INTEGRATION = GITHUB_API_INTEGRATION
  GIT_CREDENTIALS = GITHUB_SECRET
  ORIGIN = 'https://github.com/xx/snowflake_data_engineering';


ALTER SCHEMA PUBLIC RENAME TO INTEGRATION;