SET MY_USER = CURRENT_USER();
SET GITHUB_SECRET_USERNAME = '<GITHUB_SECRET_USERNAME>';
SET GITHUB_SECRET_PASSWORD = '<GITHUB_SECRET_PASSWORD>';
SET GITHUB_URL_PREFIX = 'https://github.com/username';
SET GITHUB_REPO_ORIGIN = 'https://github.com/username/snowflake_data_engineering';


--------------------------------------------------------------
-- Create account level objects
--------------------------------------------------------------
USE ROLE ACCOUNTADMIN;

-- Create Roles
CREATE OR REPLACE ROLE ROLE_DE;
GRANT ROLE ROLE_DE TO ROLE SYSADMIN;
GRANT ROLE ROLE_DE TO USER IDENTIFIER($MY_USER);

GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE ROLE_DE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE ROLE_DE;
GRANT EXECUTE MANAGED_TASK ON ACCOUNT TO ROLE ROLE_DE;
GRANT MONITOR TASK ON ACCOUNT TO ROLE ROLE_DE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE ROLE_DE;


-- Databases
CREATE OR REPLACE DATABASE SANDBOX_DB;
GRANT OWNERSHIP ON DATABASE SANDBOX_DB TO ROLE ROLE_DE;

-- warehouse
CREATE OR REPLACE WAREHOUSE SANDBOX_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_RESUME = TRUE
  AUTO_SUSPEND = 60
  INITIALLY_SUSPENDED = TRUE    
  COMMENT = 'Sandbox warehouse for data engineering';

GRANT OWNERSHIP ON WAREHOUSE SANDBOX_WH TO ROLE ROLE_DE;

-- database level objects
USE ROLE ROLE_DE;
USE DATABASE SANDBOX_DB;
USE warehouse SANDBOX_WH;

CREATE OR REPLACE SCHEMA SANDBOX_DB.INTEGRATIONS;
CREATE OR REPLACE SCHEMA SANDBOX_DB.DEV_SCHEMAS;
CREATE OR REPLACE SCHEMA SANDBOX_DB.PRO_SCHEMAS;

USE SCHEMA SANDBOX_DB.INTEGRATIONS;
-- External Frostbyte objects
CREATE OR REPLACE STAGE FROSTBYTE_RAW_STAGE
  URL = 's3://sfquickstarts/data-engineering-with-snowpark-python/'
;

CREATE OR REPLACE SECRET GITHUB_SECRET
  TYPE = password
  USERNAME = $GITHUB_SECRET_USERNAME
  PASSWORD = $GITHUB_SECRET_PASSWORD;

-- API Integration at account level
-- This integration is used to connect to the GitHub API
CREATE OR REPLACE API INTEGRATION GITHUB_API_INTEGRATION
  API_PROVIDER = GIT_HTTPS_API
  API_ALLOWED_PREFIXES = ($GITHUB_URL_PREFIX)
  ALLOWED_AUTHENTICATION_SECRETS = (GITHUB_SECRET)
  ENABLED = TRUE;

-- Git Repository
CREATE OR REPLACE GIT REPOSITORY GIT_REPO
  API_INTEGRATION = GITHUB_API_INTEGRATION
  GIT_CREDENTIALS = GITHUB_SECRET
  ORIGIN = $GITHUB_REPO_ORIGIN;

  ---------------------------------------------------------------
  -- Create the event table
  ---------------------------------------------------------------
  USE ROLE ACCOUNTADMIN;
  CREATE EVENT TABLE SANDBOX_DB.INTEGRATIONS.EVENTS;
  GRANT SELECT, INSERT ON TABLE SANDBOX_DB.INTEGRATIONS.EVENTS TO ROLE ROLE_DE;
  ALTER ACCOUNT SET EVENT_TABLE = SANDBOX_DB.INTEGRATIONS.EVENTS;
  ALTER DATABASE SANDBOX_DB SET LOG_LEVEL = INFO;


